[package]
name = "stellar_binary_search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
firestore = "0.31"


[[bin]]
name = "stellar_binary_search"
path = "src/main.rs"

[profile.dev]
opt-level = 0